---
- hosts: all
  become: yes
  vars:
    storm:
      version: 1.1.1
      mirror: http://www-us.apache.org/dist
      user: storm
      group: root
      install_dir: /opt
      base_dir: /opt/storm
      log_dir: /opt/storm-log

  tasks:

  - include: init_java.yml
  - include: init_storm.yml
  - include: init_network.yml

  - name: Nimbus | Set config
    template:
      src: "templates/storm/nimbus/storm.yaml"
      dest: "{{storm.install_dir}}/apache-storm-{{ storm.version }}/conf/"

  - name: Nimbus | Run Nimbus
    shell: ./storm nimbus &
    become: true
    become_user: root
    args:
      chdir: "{{storm.install_dir}}/apache-storm-{{storm.version}}/bin/"
      executable: /bin/bash

